<a href="https://colab.research.google.com/github/ARJUN108-verma/NumPy/blob/main/17_problem_%26_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
!pip install numpy


In [18]:
import numpy as np

Create a 1D NumPy array of numbers from 10 to 50.


In [19]:
ar = np.arange(10,51)
print(ar)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Create a 3x3 identity matrix.


In [20]:
ar1 = np.array([1,1,3,4,5], ndmin= 3)
print(ar1)

[[[1 1 3 4 5]]]


Create a 5x5 matrix filled with the number 7.


In [21]:
ar2 = np.full((5,5),7)
ar2

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

Generate a 1D array of 10 random integers between 1 and 100.


In [22]:
ar3 = np.random.randint(1,100, size = 10)
ar3

array([91, 19, 65,  4, 90, 90, 32, 89,  1, 78])

Reshape a 1D array of 12 elements into a 3x4 matrix.


In [23]:
ar4 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ar4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
ar4.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Get the mean, median, and standard deviation of an array.


In [25]:
#mean
ar4.mean()

np.float64(6.5)

In [28]:
#median
np.median(ar4)

np.float64(6.5)

In [29]:
#standard deviation
np.std(ar4)

np.float64(3.452052529534663)

Find all elements greater than 5 in a given array.


In [30]:
grtn_5 = ar4[ar4 > 5]
grtn_5

array([ 6,  7,  8,  9, 10, 11, 12])

Create two arrays and perform element-wise multiplication.


In [32]:
a = np.array([2,4,6,8,10])
b = np.array([1,3,5,7,9])
mult = a*b
print(mult)

[ 2 12 30 56 90]


Replace all odd numbers in an array with -1.


In [34]:
ar4[ar4 % 2 != 0] = -1
ar4

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12])

Stack two arrays vertically and horizontally.


In [35]:
#vertically
v_stack = np.vstack((a,b))
print(v_stack)

[[ 2  4  6  8 10]
 [ 1  3  5  7  9]]


In [36]:
#horizontally
h_stack = np.hstack((a,b))
print(h_stack)

[ 2  4  6  8 10  1  3  5  7  9]


Find the square root and exponential of all array elements.


In [37]:
#square root
np.sqrt(a)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766])

In [38]:
#exponential
np.exp(b)

array([2.71828183e+00, 2.00855369e+01, 1.48413159e+02, 1.09663316e+03,
       8.10308393e+03])

Create a boolean array that identifies even numbers in a given array.

In [40]:
#even
ev1 = b % 2 == 0
ev1

array([False, False, False, False, False])

In [41]:
ev2 = a % 2 == 0
ev2

array([ True,  True,  True,  True,  True])

Get the index of the maximum and minimum value in an array.

In [43]:
#maximum values index
np.argmax(ar4)

np.int64(11)

In [44]:
#minimum values index
np.argmin(ar4)

np.int64(0)